### ISSUE TITLE
Can I download a compiled .jar for run in ubuntu terminal?

### ISSUE THREAD

**Issue by pedrofsn** [MathBunny/newton-raphson#8]
NewtonRaphsonApp.java is not working. When I try to run the project, is what I get:

[Print](https://www.dropbox.com/s/mdopr703cybr6cz/print.png?dl=0)

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
> 	at javax.imageio.ImageIO.read(ImageIO.java:1388)
> 	at classes.NewtonRaphsonApp.fetchImages(NewtonRaphsonApp.java:79)
> 	at classes.NewtonRaphsonApp.paint(NewtonRaphsonApp.java:152)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
> 	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
> 	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
> 	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
> 	at javax.imageio.ImageIO.read(ImageIO.java:1388)
> 	at classes.NewtonRaphsonApp.fetchImages(NewtonRaphsonApp.java:79)
> 	at classes.NewtonRaphsonApp.paint(NewtonRaphsonApp.java:152)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)
> 	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
> 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
> 	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
> 	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
> 	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by MathBunny** [comment]
Looks like it doesn't have access to the background image. Is the background image in the directory?

**Comment by pedrofsn** [comment]
Hi @MathBunny, I just cloned the repository and run the project. How is the name of image? I can search for this here to confirm.

**Comment by MathBunny** [comment]
In the `/images`, do you see images?

**Comment by pedrofsn** [comment]
I've this images on folder /images:

- About.jpg
- About.pxm
- CalculatorBackground.jpg
- CalculatorBackground.pxm
- highlight.jpg
- highlight.png
- highlight.pxm
- initializing.jpg
- monitor.jpg
- monitor_max.jpg
- monitor.png
- monitor.pxm
- off.jpg
- StartStopValue.png
- StartStopValue.pxm

**Comment by MathBunny** [comment]
I would recommend running the console version in this case, it should work. I'm still not aware of why it doesn't work with the graphics though.

**Comment by pedrofsn** [comment]
@MathBunny I built other environment in other computer. The project on visual version has runned and showed the background. So, the problem for background probably was my previous environment. You can close this issue. :+1:

**Comment by MathBunny** [comment]
Okay! Glad to hear this was fixed
